### ISSUE TITLE
Not performing well when duplicate points appear.

### ISSUE THREAD

**Issue by Hezip** [SMRT-AIST/fast_gicp#6]
**Thanks for your attention**, I encountered two problems:

- Not able to converge in all cases even though the matching score was high.

- Not performing well when duplicate points appear. The test [.pcd] (https://drive.google.com/open?id=1aQjl0Pf8HW0tGF9ss3jZVvq6aX-KYVom) is here.

When I am using the **octree.approxNearestSearch** algorithm of PCL, duplicate points will be found and added to the point cloud. The GICP_MT and VGICP methods do not work well in this situation. _But the algorithm of PCL library works well._

I am looking forward to the answer and thank you again!

**Comment by koide3** [comment]
Hi @Hezip ,
Thank you for reporting the issue. Let me confirm that you replaced kdtree.nearestKSearch with octree.approxNearestSearch, then GICP_MT and VGICP didn't work well, right? Can you share your modified code so that I can test it?

**Comment by Hezip** [comment]
No code changes.
One of the point cloud I provided was obtained through octree.approxNearestSearch, and there are duplicate points in it.

**Comment by koide3** [comment]
I suppose the cause is the number of points rather than duplicate points. We employed a GaussNewton solver that is fast but sometimes a bit unstable with respect to a large number of points. I applied an approx voxel grid filter (gridsize=0.1m) to your point clouds, then the algorithm worked. We empirically found that the algorithm can be unstable when # of points > 15k.

**Comment by Hezip** [comment]
Thank you very much for your answer. After I remove the duplicate points, the effect is better, but I think you are right, it should be related to the GaussNewton solver.
